-- ============================================================================
-- TELECOM CHURN DATASET - 20 SQL INTERVIEW QUESTIONS & SOLUTIONS
-- Covers: GROUP BY, JOIN, CASE, CTE, Window Functions, Subqueries, Business KPIs
-- ============================================================================

-- Table Schema Assumption:
-- customers (customer_id, gender, tenure, contract, internet_service, payment_method, monthly_charges, total_charges, churn)
-- customer_services (service_id, customer_id, tech_support, streaming_tv, paperless_billing)
-- billing_history (bill_id, customer_id, billing_date, amount_paid)


-- ============================================================================
-- CATEGORY 1: GROUP BY & AGGREGATIONS (Questions 1 - 4)
-- ============================================================================

-- Q1: Calculate the total customer count and churn rate grouped by Contract type.
SELECT 
    contract,
    COUNT(customer_id) AS total_customers,
    SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(customer_id), 2) AS churn_rate_pct
FROM customers
GROUP BY contract
ORDER BY churn_rate_pct DESC;

-- Q2: Find the average monthly charges and total monthly revenue generated by each Internet Service provider.
SELECT 
    internet_service,
    COUNT(customer_id) AS active_subscribers,
    ROUND(AVG(monthly_charges), 2) AS avg_monthly_charge,
    ROUND(SUM(monthly_charges), 2) AS total_monthly_revenue
FROM customers
GROUP BY internet_service
ORDER BY total_monthly_revenue DESC;

-- Q3: Determine the churn count and average tenure for each Payment Method.
SELECT 
    payment_method,
    COUNT(customer_id) AS total_customers,
    SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) AS churn_count,
    ROUND(AVG(tenure), 1) AS avg_tenure_months
FROM customers
GROUP BY payment_method
ORDER BY churn_count DESC;

-- Q4: Identify demographic churn distribution by Gender and Contract type.
SELECT 
    gender,
    contract,
    COUNT(customer_id) AS total_customers,
    SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers
FROM customers
GROUP BY gender, contract
ORDER BY gender, total_customers DESC;


-- ============================================================================
-- CATEGORY 2: JOINs (Questions 5 - 7)
-- ============================================================================

-- Q5: List all customers who have 'Fiber optic' service along with their Tech Support subscription status using an INNER JOIN.
SELECT 
    c.customer_id,
    c.contract,
    c.monthly_charges,
    s.tech_support,
    c.churn
FROM customers c
INNER JOIN customer_services s ON c.customer_id = s.customer_id
WHERE c.internet_service = 'Fiber optic';

-- Q6: Find customers who have billing history records, showing their total lifetime payments vs monthly charges.
SELECT 
    c.customer_id,
    c.monthly_charges,
    SUM(b.amount_paid) AS total_amount_paid,
    COUNT(b.bill_id) AS total_bills_issued
FROM customers c
LEFT JOIN billing_history b ON c.customer_id = b.customer_id
GROUP BY c.customer_id, c.monthly_charges;

-- Q7: Identify customers who have NOT made any billing payments using a LEFT JOIN with a NULL check.
SELECT 
    c.customer_id,
    c.contract,
    c.payment_method
FROM customers c
LEFT JOIN billing_history b ON c.customer_id = b.customer_id
WHERE b.bill_id IS NULL;


-- ============================================================================
-- CATEGORY 3: CASE STATEMENTS (Questions 8 - 10)
-- ============================================================================

-- Q8: Categorize customers into tenure segments ('New (<12 mo)', 'Loyal (1-3 yrs)', 'Veteran (>3 yrs)') and calculate churn rate per segment.
SELECT 
    CASE 
        WHEN tenure < 12 THEN '1. New (<12 mo)'
        WHEN tenure BETWEEN 12 AND 36 THEN '2. Loyal (1-3 yrs)'
        ELSE '3. Veteran (>3 yrs)'
    END AS tenure_segment,
    COUNT(customer_id) AS total_customers,
    SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) AS churned_count,
    ROUND(SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(customer_id), 2) AS segment_churn_rate
FROM customers
GROUP BY 1
ORDER BY 1;

-- Q9: Segment customers by monthly billing tiers ('Low < $50', 'Medium $50-$90', 'High > $90') and find average tenure.
SELECT 
    CASE 
        WHEN monthly_charges < 50 THEN 'Low (<$50)'
        WHEN monthly_charges BETWEEN 50 AND 90 THEN 'Medium ($50-$90)'
        ELSE 'High (>$90)'
    END AS charge_tier,
    COUNT(customer_id) AS customer_count,
    ROUND(AVG(tenure), 1) AS avg_tenure
FROM customers
GROUP BY 1
ORDER BY avg_tenure DESC;

-- Q10: Create a risk score label based on contract type, paperless billing, and payment method.
SELECT 
    customer_id,
    contract,
    payment_method,
    CASE 
        WHEN contract = 'Month-to-month' AND payment_method = 'Electronic check' THEN 'High Risk'
        WHEN contract = 'Two year' THEN 'Low Risk'
        ELSE 'Medium Risk'
    END AS churn_risk_score
FROM customers;


-- ============================================================================
-- CATEGORY 4: COMMON TABLE EXPRESSIONS - CTEs (Questions 11 - 13)
-- ============================================================================

-- Q11: Use a CTE to find customers whose monthly charges are higher than the overall average monthly charge.
WITH AvgCharges AS (
    SELECT AVG(monthly_charges) AS overall_avg FROM customers
)
SELECT c.customer_id, c.monthly_charges, c.contract, c.churn
FROM customers c, AvgCharges ac
WHERE c.monthly_charges > ac.overall_avg
ORDER BY c.monthly_charges DESC;

-- Q12: Use a CTE to calculate the total revenue per contract type and filter contracts generating > $100,000.
WITH ContractRevenue AS (
    SELECT contract, SUM(monthly_charges) AS total_rev, COUNT(customer_id) AS cnt
    FROM customers
    GROUP BY contract
)
SELECT contract, cnt AS total_customers, ROUND(total_rev, 2) AS total_revenue
FROM ContractRevenue
WHERE total_rev > 50000
ORDER BY total_revenue DESC;

-- Q13: Use multiple CTEs to compare churn rate of customers with Tech Support vs without Tech Support.
WITH TechSupportYes AS (
    SELECT COUNT(*) AS total, SUM(CASE WHEN c.churn='Yes' THEN 1 ELSE 0 END) AS churned
    FROM customers c JOIN customer_services s ON c.customer_id = s.customer_id
    WHERE s.tech_support = 'Yes'
),
TechSupportNo AS (
    SELECT COUNT(*) AS total, SUM(CASE WHEN c.churn='Yes' THEN 1 ELSE 0 END) AS churned
    FROM customers c JOIN customer_services s ON c.customer_id = s.customer_id
    WHERE s.tech_support = 'No'
)
SELECT 'With Tech Support' AS support_status, churned * 100.0 / total AS churn_pct FROM TechSupportYes
UNION ALL
SELECT 'Without Tech Support', churned * 100.0 / total FROM TechSupportNo;


-- ============================================================================
-- CATEGORY 5: WINDOW FUNCTIONS (Questions 14 - 16)
-- ============================================================================

-- Q14: Rank customers within each Internet Service category by monthly charges using RANK().
SELECT 
    customer_id,
    internet_service,
    monthly_charges,
    RANK() OVER (PARTITION BY internet_service ORDER BY monthly_charges DESC) AS charge_rank_in_service
FROM customers;

-- Q15: Calculate running total of monthly revenue ordered by tenure using SUM() window function.
SELECT 
    customer_id,
    tenure,
    monthly_charges,
    SUM(monthly_charges) OVER (ORDER BY tenure ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running_revenue
FROM customers;

-- Q16: Compare each customer's monthly charges against the average monthly charges of their specific contract type using AVG() OVER().
SELECT 
    customer_id,
    contract,
    monthly_charges,
    ROUND(AVG(monthly_charges) OVER (PARTITION BY contract), 2) AS avg_contract_charge,
    ROUND(monthly_charges - AVG(monthly_charges) OVER (PARTITION BY contract), 2) AS diff_from_contract_avg
FROM customers;


-- ============================================================================
-- CATEGORY 6: SUBQUERIES (Questions 17 - 18)
-- ============================================================================

-- Q17: Find customers who pay higher monthly charges than the maximum monthly charge of customers with 'Two year' contracts.
SELECT customer_id, contract, monthly_charges
FROM customers
WHERE monthly_charges > (
    SELECT MAX(monthly_charges) 
    FROM customers 
    WHERE contract = 'Two year'
);

-- Q18: Identify customers who belong to the payment method with the highest overall churn rate using a subquery.
SELECT customer_id, payment_method, monthly_charges, churn
FROM customers
WHERE payment_method = (
    SELECT payment_method
    FROM customers
    GROUP BY payment_method
    ORDER BY SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*) DESC
    LIMIT 1
);


-- ============================================================================
-- CATEGORY 7: ADVANCED BUSINESS QUESTIONS (Questions 19 - 20)
-- ============================================================================

-- Q19: Calculate Customer Lifetime Value (CLV) approximation: (Tenure * Monthly Charges) and find the top 5 highest value churned customers.
SELECT 
    customer_id,
    contract,
    tenure,
    monthly_charges,
    ROUND(tenure * monthly_charges, 2) AS estimated_clv
FROM customers
WHERE churn = 'Yes'
ORDER BY estimated_clv DESC
LIMIT 5;

-- Q20: Create a comprehensive monthly retention summary table showing retained vs churned counts, revenue lost to churn, and retention percentage per contract type.
SELECT 
    contract,
    COUNT(customer_id) AS total_customers,
    SUM(CASE WHEN churn = 'No' THEN 1 ELSE 0 END) AS retained_customers,
    SUM(CASE WHEN churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(SUM(CASE WHEN churn = 'Yes' THEN monthly_charges ELSE 0 END), 2) AS monthly_revenue_lost,
    ROUND(SUM(CASE WHEN churn = 'No' THEN 1 ELSE 0 END) * 100.0 / COUNT(customer_id), 2) AS retention_rate_pct
FROM customers
GROUP BY contract
ORDER BY retention_rate_pct DESC;
